<?xml version="1.0" encoding="utf-8"?><Database Name="dbGameHocTap" Class="dbcsdlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=msi\td;Initial Catalog=dbGameHocTap;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dbGameHocTapConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbGameChinhTa" Member="tbGameChinhTas">
    <Type Name="tbGameChinhTa">
      <Column Name="gamechinhta_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gamechinhta_noidung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gamechinhta_dapan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gamechinhta_dapansai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbTaiKhoan" Member="tbTaiKhoans">
    <Type Name="tbTaiKhoan">
      <Column Name="taikhoan_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taikhoan_hoten" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taikhoan_tentaikhoan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="taikhoan_matkhau" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taikhoan_hinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="taikhoan_gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="taikhoan_ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbGameDuoiHinhBatChu" Member="tbGameDuoiHinhBatChus">
    <Type Name="tbGameDuoiHinhBatChu">
      <Column Name="duoihinhbatchu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="duoihinhbatchu_hinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="duoihinhbatchu_dapan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbKhoiLop" Member="tbKhoiLops">
    <Type Name="tbKhoiLop">
      <Column Name="khoilop_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="khoilop_khoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbManGame" Member="tbManGames">
    <Type Name="tbManGame">
      <Column Name="mangame_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mangame_man" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="khoilop_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="khoilop_khoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>