#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHangg
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbQuanLyQuanCafe")]
	public partial class dbcsdlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbBan(tbBan instance);
    partial void UpdatetbBan(tbBan instance);
    partial void DeletetbBan(tbBan instance);
    partial void InserttbTinTuc(tbTinTuc instance);
    partial void UpdatetbTinTuc(tbTinTuc instance);
    partial void DeletetbTinTuc(tbTinTuc instance);
    partial void InserttbBaner(tbBaner instance);
    partial void UpdatetbBaner(tbBaner instance);
    partial void DeletetbBaner(tbBaner instance);
    partial void InserttbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void UpdatetbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void DeletetbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void InserttbGameSapXepCauThanhNgu(tbGameSapXepCauThanhNgu instance);
    partial void UpdatetbGameSapXepCauThanhNgu(tbGameSapXepCauThanhNgu instance);
    partial void DeletetbGameSapXepCauThanhNgu(tbGameSapXepCauThanhNgu instance);
    partial void InserttbHoaDon(tbHoaDon instance);
    partial void UpdatetbHoaDon(tbHoaDon instance);
    partial void DeletetbHoaDon(tbHoaDon instance);
    partial void InserttbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void UpdatetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void DeletetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void InserttbLoaiBan(tbLoaiBan instance);
    partial void UpdatetbLoaiBan(tbLoaiBan instance);
    partial void DeletetbLoaiBan(tbLoaiBan instance);
    partial void InserttbLoaiSanPham(tbLoaiSanPham instance);
    partial void UpdatetbLoaiSanPham(tbLoaiSanPham instance);
    partial void DeletetbLoaiSanPham(tbLoaiSanPham instance);
    partial void InserttbLoaiTinTuc(tbLoaiTinTuc instance);
    partial void UpdatetbLoaiTinTuc(tbLoaiTinTuc instance);
    partial void DeletetbLoaiTinTuc(tbLoaiTinTuc instance);
    partial void InserttbNhapHang(tbNhapHang instance);
    partial void UpdatetbNhapHang(tbNhapHang instance);
    partial void DeletetbNhapHang(tbNhapHang instance);
    partial void InserttbNhapHangChiTiet(tbNhapHangChiTiet instance);
    partial void UpdatetbNhapHangChiTiet(tbNhapHangChiTiet instance);
    partial void DeletetbNhapHangChiTiet(tbNhapHangChiTiet instance);
    partial void InserttbSanPham(tbSanPham instance);
    partial void UpdatetbSanPham(tbSanPham instance);
    partial void DeletetbSanPham(tbSanPham instance);
    partial void InserttbTaiKhoan(tbTaiKhoan instance);
    partial void UpdatetbTaiKhoan(tbTaiKhoan instance);
    partial void DeletetbTaiKhoan(tbTaiKhoan instance);
    partial void InserttbGameChinhTa(tbGameChinhTa instance);
    partial void UpdatetbGameChinhTa(tbGameChinhTa instance);
    partial void DeletetbGameChinhTa(tbGameChinhTa instance);
    #endregion
		
		public dbcsdlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbQuanLyQuanCafeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbBan> tbBans
		{
			get
			{
				return this.GetTable<tbBan>();
			}
		}
		
		public System.Data.Linq.Table<tbTinTuc> tbTinTucs
		{
			get
			{
				return this.GetTable<tbTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<tbBaner> tbBaners
		{
			get
			{
				return this.GetTable<tbBaner>();
			}
		}
		
		public System.Data.Linq.Table<tbGameDuoiHinhBatChu> tbGameDuoiHinhBatChus
		{
			get
			{
				return this.GetTable<tbGameDuoiHinhBatChu>();
			}
		}
		
		public System.Data.Linq.Table<tbGameSapXepCauThanhNgu> tbGameSapXepCauThanhNgus
		{
			get
			{
				return this.GetTable<tbGameSapXepCauThanhNgu>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDon> tbHoaDons
		{
			get
			{
				return this.GetTable<tbHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDonChiTiet> tbHoaDonChiTiets
		{
			get
			{
				return this.GetTable<tbHoaDonChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbLoaiBan> tbLoaiBans
		{
			get
			{
				return this.GetTable<tbLoaiBan>();
			}
		}
		
		public System.Data.Linq.Table<tbLoaiSanPham> tbLoaiSanPhams
		{
			get
			{
				return this.GetTable<tbLoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tbLoaiTinTuc> tbLoaiTinTucs
		{
			get
			{
				return this.GetTable<tbLoaiTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<tbNhapHang> tbNhapHangs
		{
			get
			{
				return this.GetTable<tbNhapHang>();
			}
		}
		
		public System.Data.Linq.Table<tbNhapHangChiTiet> tbNhapHangChiTiets
		{
			get
			{
				return this.GetTable<tbNhapHangChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbSanPham> tbSanPhams
		{
			get
			{
				return this.GetTable<tbSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tbTaiKhoan> tbTaiKhoans
		{
			get
			{
				return this.GetTable<tbTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tbGameChinhTa> tbGameChinhTas
		{
			get
			{
				return this.GetTable<tbGameChinhTa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbBan")]
	public partial class tbBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ban_id;
		
		private string _ban_ten;
		
		private string _ban_trangthai;
		
		private System.Nullable<int> _loaiban_id;
		
		private string _loaiban_tenban;
		
		private System.Nullable<int> _sanpham_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onban_idChanging(int value);
    partial void Onban_idChanged();
    partial void Onban_tenChanging(string value);
    partial void Onban_tenChanged();
    partial void Onban_trangthaiChanging(string value);
    partial void Onban_trangthaiChanged();
    partial void Onloaiban_idChanging(System.Nullable<int> value);
    partial void Onloaiban_idChanged();
    partial void Onloaiban_tenbanChanging(string value);
    partial void Onloaiban_tenbanChanged();
    partial void Onsanpham_idChanging(System.Nullable<int> value);
    partial void Onsanpham_idChanged();
    #endregion
		
		public tbBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_ten", DbType="NVarChar(MAX)")]
		public string ban_ten
		{
			get
			{
				return this._ban_ten;
			}
			set
			{
				if ((this._ban_ten != value))
				{
					this.Onban_tenChanging(value);
					this.SendPropertyChanging();
					this._ban_ten = value;
					this.SendPropertyChanged("ban_ten");
					this.Onban_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_trangthai", DbType="NVarChar(MAX)")]
		public string ban_trangthai
		{
			get
			{
				return this._ban_trangthai;
			}
			set
			{
				if ((this._ban_trangthai != value))
				{
					this.Onban_trangthaiChanging(value);
					this.SendPropertyChanging();
					this._ban_trangthai = value;
					this.SendPropertyChanged("ban_trangthai");
					this.Onban_trangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiban_id", DbType="Int")]
		public System.Nullable<int> loaiban_id
		{
			get
			{
				return this._loaiban_id;
			}
			set
			{
				if ((this._loaiban_id != value))
				{
					this.Onloaiban_idChanging(value);
					this.SendPropertyChanging();
					this._loaiban_id = value;
					this.SendPropertyChanged("loaiban_id");
					this.Onloaiban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiban_tenban", DbType="NVarChar(MAX)")]
		public string loaiban_tenban
		{
			get
			{
				return this._loaiban_tenban;
			}
			set
			{
				if ((this._loaiban_tenban != value))
				{
					this.Onloaiban_tenbanChanging(value);
					this.SendPropertyChanging();
					this._loaiban_tenban = value;
					this.SendPropertyChanged("loaiban_tenban");
					this.Onloaiban_tenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int")]
		public System.Nullable<int> sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTinTuc")]
	public partial class tbTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tintuc_id;
		
		private string _tintuc_tieude;
		
		private string _tintuc_noidung;
		
		private System.Nullable<System.DateTime> _tintuc_ngaytao;
		
		private System.Nullable<int> _loaitintuc_id;
		
		private string _tintuc_hinhanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontintuc_idChanging(int value);
    partial void Ontintuc_idChanged();
    partial void Ontintuc_tieudeChanging(string value);
    partial void Ontintuc_tieudeChanged();
    partial void Ontintuc_noidungChanging(string value);
    partial void Ontintuc_noidungChanged();
    partial void Ontintuc_ngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void Ontintuc_ngaytaoChanged();
    partial void Onloaitintuc_idChanging(System.Nullable<int> value);
    partial void Onloaitintuc_idChanged();
    partial void Ontintuc_hinhanhChanging(string value);
    partial void Ontintuc_hinhanhChanged();
    #endregion
		
		public tbTinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tintuc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tintuc_id
		{
			get
			{
				return this._tintuc_id;
			}
			set
			{
				if ((this._tintuc_id != value))
				{
					this.Ontintuc_idChanging(value);
					this.SendPropertyChanging();
					this._tintuc_id = value;
					this.SendPropertyChanged("tintuc_id");
					this.Ontintuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tintuc_tieude", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string tintuc_tieude
		{
			get
			{
				return this._tintuc_tieude;
			}
			set
			{
				if ((this._tintuc_tieude != value))
				{
					this.Ontintuc_tieudeChanging(value);
					this.SendPropertyChanging();
					this._tintuc_tieude = value;
					this.SendPropertyChanged("tintuc_tieude");
					this.Ontintuc_tieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tintuc_noidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string tintuc_noidung
		{
			get
			{
				return this._tintuc_noidung;
			}
			set
			{
				if ((this._tintuc_noidung != value))
				{
					this.Ontintuc_noidungChanging(value);
					this.SendPropertyChanging();
					this._tintuc_noidung = value;
					this.SendPropertyChanged("tintuc_noidung");
					this.Ontintuc_noidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tintuc_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> tintuc_ngaytao
		{
			get
			{
				return this._tintuc_ngaytao;
			}
			set
			{
				if ((this._tintuc_ngaytao != value))
				{
					this.Ontintuc_ngaytaoChanging(value);
					this.SendPropertyChanging();
					this._tintuc_ngaytao = value;
					this.SendPropertyChanged("tintuc_ngaytao");
					this.Ontintuc_ngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaitintuc_id", DbType="Int")]
		public System.Nullable<int> loaitintuc_id
		{
			get
			{
				return this._loaitintuc_id;
			}
			set
			{
				if ((this._loaitintuc_id != value))
				{
					this.Onloaitintuc_idChanging(value);
					this.SendPropertyChanging();
					this._loaitintuc_id = value;
					this.SendPropertyChanged("loaitintuc_id");
					this.Onloaitintuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tintuc_hinhanh", DbType="NVarChar(MAX)")]
		public string tintuc_hinhanh
		{
			get
			{
				return this._tintuc_hinhanh;
			}
			set
			{
				if ((this._tintuc_hinhanh != value))
				{
					this.Ontintuc_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._tintuc_hinhanh = value;
					this.SendPropertyChanged("tintuc_hinhanh");
					this.Ontintuc_hinhanhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbBaner")]
	public partial class tbBaner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _banner_id;
		
		private string _banner_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbanner_idChanging(int value);
    partial void Onbanner_idChanged();
    partial void Onbanner_imageChanging(string value);
    partial void Onbanner_imageChanged();
    #endregion
		
		public tbBaner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banner_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int banner_id
		{
			get
			{
				return this._banner_id;
			}
			set
			{
				if ((this._banner_id != value))
				{
					this.Onbanner_idChanging(value);
					this.SendPropertyChanging();
					this._banner_id = value;
					this.SendPropertyChanged("banner_id");
					this.Onbanner_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banner_image", DbType="NVarChar(MAX)")]
		public string banner_image
		{
			get
			{
				return this._banner_image;
			}
			set
			{
				if ((this._banner_image != value))
				{
					this.Onbanner_imageChanging(value);
					this.SendPropertyChanging();
					this._banner_image = value;
					this.SendPropertyChanged("banner_image");
					this.Onbanner_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbGameDuoiHinhBatChu")]
	public partial class tbGameDuoiHinhBatChu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _duoihinhbatchu_id;
		
		private string _duoihinhbatchu_hinhanh;
		
		private string _duoihinhbatchu_dapan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onduoihinhbatchu_idChanging(int value);
    partial void Onduoihinhbatchu_idChanged();
    partial void Onduoihinhbatchu_hinhanhChanging(string value);
    partial void Onduoihinhbatchu_hinhanhChanged();
    partial void Onduoihinhbatchu_dapanChanging(string value);
    partial void Onduoihinhbatchu_dapanChanged();
    #endregion
		
		public tbGameDuoiHinhBatChu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int duoihinhbatchu_id
		{
			get
			{
				return this._duoihinhbatchu_id;
			}
			set
			{
				if ((this._duoihinhbatchu_id != value))
				{
					this.Onduoihinhbatchu_idChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_id = value;
					this.SendPropertyChanged("duoihinhbatchu_id");
					this.Onduoihinhbatchu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_hinhanh", DbType="NVarChar(MAX)")]
		public string duoihinhbatchu_hinhanh
		{
			get
			{
				return this._duoihinhbatchu_hinhanh;
			}
			set
			{
				if ((this._duoihinhbatchu_hinhanh != value))
				{
					this.Onduoihinhbatchu_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_hinhanh = value;
					this.SendPropertyChanged("duoihinhbatchu_hinhanh");
					this.Onduoihinhbatchu_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_dapan", DbType="NVarChar(MAX)")]
		public string duoihinhbatchu_dapan
		{
			get
			{
				return this._duoihinhbatchu_dapan;
			}
			set
			{
				if ((this._duoihinhbatchu_dapan != value))
				{
					this.Onduoihinhbatchu_dapanChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_dapan = value;
					this.SendPropertyChanged("duoihinhbatchu_dapan");
					this.Onduoihinhbatchu_dapanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbGameSapXepCauThanhNgu")]
	public partial class tbGameSapXepCauThanhNgu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cauthanhngu_id;
		
		private string _cauthanhngu_dapan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncauthanhngu_idChanging(int value);
    partial void Oncauthanhngu_idChanged();
    partial void Oncauthanhngu_dapanChanging(string value);
    partial void Oncauthanhngu_dapanChanged();
    #endregion
		
		public tbGameSapXepCauThanhNgu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cauthanhngu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cauthanhngu_id
		{
			get
			{
				return this._cauthanhngu_id;
			}
			set
			{
				if ((this._cauthanhngu_id != value))
				{
					this.Oncauthanhngu_idChanging(value);
					this.SendPropertyChanging();
					this._cauthanhngu_id = value;
					this.SendPropertyChanged("cauthanhngu_id");
					this.Oncauthanhngu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cauthanhngu_dapan", DbType="NVarChar(MAX)")]
		public string cauthanhngu_dapan
		{
			get
			{
				return this._cauthanhngu_dapan;
			}
			set
			{
				if ((this._cauthanhngu_dapan != value))
				{
					this.Oncauthanhngu_dapanChanging(value);
					this.SendPropertyChanging();
					this._cauthanhngu_dapan = value;
					this.SendPropertyChanged("cauthanhngu_dapan");
					this.Oncauthanhngu_dapanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDon")]
	public partial class tbHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoadon_id;
		
		private System.Nullable<System.DateTime> _hoadon_ngaynhap;
		
		private System.Nullable<System.DateTime> _hoadon_ngayxuat;
		
		private string _hoadon_mahoadon;
		
		private System.Nullable<int> _ban_id;
		
		private System.Nullable<int> _hoadon_trangthai;
		
		private System.Nullable<int> _hoadon_tongtien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoadon_idChanging(int value);
    partial void Onhoadon_idChanged();
    partial void Onhoadon_ngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void Onhoadon_ngaynhapChanged();
    partial void Onhoadon_ngayxuatChanging(System.Nullable<System.DateTime> value);
    partial void Onhoadon_ngayxuatChanged();
    partial void Onhoadon_mahoadonChanging(string value);
    partial void Onhoadon_mahoadonChanged();
    partial void Onban_idChanging(System.Nullable<int> value);
    partial void Onban_idChanged();
    partial void Onhoadon_trangthaiChanging(System.Nullable<int> value);
    partial void Onhoadon_trangthaiChanged();
    partial void Onhoadon_tongtienChanging(System.Nullable<int> value);
    partial void Onhoadon_tongtienChanged();
    #endregion
		
		public tbHoaDon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> hoadon_ngaynhap
		{
			get
			{
				return this._hoadon_ngaynhap;
			}
			set
			{
				if ((this._hoadon_ngaynhap != value))
				{
					this.Onhoadon_ngaynhapChanging(value);
					this.SendPropertyChanging();
					this._hoadon_ngaynhap = value;
					this.SendPropertyChanged("hoadon_ngaynhap");
					this.Onhoadon_ngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_ngayxuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> hoadon_ngayxuat
		{
			get
			{
				return this._hoadon_ngayxuat;
			}
			set
			{
				if ((this._hoadon_ngayxuat != value))
				{
					this.Onhoadon_ngayxuatChanging(value);
					this.SendPropertyChanging();
					this._hoadon_ngayxuat = value;
					this.SendPropertyChanged("hoadon_ngayxuat");
					this.Onhoadon_ngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_mahoadon", DbType="NVarChar(MAX)")]
		public string hoadon_mahoadon
		{
			get
			{
				return this._hoadon_mahoadon;
			}
			set
			{
				if ((this._hoadon_mahoadon != value))
				{
					this.Onhoadon_mahoadonChanging(value);
					this.SendPropertyChanging();
					this._hoadon_mahoadon = value;
					this.SendPropertyChanged("hoadon_mahoadon");
					this.Onhoadon_mahoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", DbType="Int")]
		public System.Nullable<int> ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_trangthai", DbType="Int")]
		public System.Nullable<int> hoadon_trangthai
		{
			get
			{
				return this._hoadon_trangthai;
			}
			set
			{
				if ((this._hoadon_trangthai != value))
				{
					this.Onhoadon_trangthaiChanging(value);
					this.SendPropertyChanging();
					this._hoadon_trangthai = value;
					this.SendPropertyChanged("hoadon_trangthai");
					this.Onhoadon_trangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_tongtien", DbType="Int")]
		public System.Nullable<int> hoadon_tongtien
		{
			get
			{
				return this._hoadon_tongtien;
			}
			set
			{
				if ((this._hoadon_tongtien != value))
				{
					this.Onhoadon_tongtienChanging(value);
					this.SendPropertyChanging();
					this._hoadon_tongtien = value;
					this.SendPropertyChanged("hoadon_tongtien");
					this.Onhoadon_tongtienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDonChiTiet")]
	public partial class tbHoaDonChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoadonchitiet_id;
		
		private System.Nullable<int> _hoadon_id;
		
		private System.Nullable<int> _sanpham_id;
		
		private System.Nullable<int> _sanpham_soluong;
		
		private System.Nullable<decimal> _sanpham_dongia;
		
		private System.Nullable<decimal> _hoadonchitiet_thanhtien;
		
		private System.Nullable<int> _ban_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoadonchitiet_idChanging(int value);
    partial void Onhoadonchitiet_idChanged();
    partial void Onhoadon_idChanging(System.Nullable<int> value);
    partial void Onhoadon_idChanged();
    partial void Onsanpham_idChanging(System.Nullable<int> value);
    partial void Onsanpham_idChanged();
    partial void Onsanpham_soluongChanging(System.Nullable<int> value);
    partial void Onsanpham_soluongChanged();
    partial void Onsanpham_dongiaChanging(System.Nullable<decimal> value);
    partial void Onsanpham_dongiaChanged();
    partial void Onhoadonchitiet_thanhtienChanging(System.Nullable<decimal> value);
    partial void Onhoadonchitiet_thanhtienChanged();
    partial void Onban_idChanging(System.Nullable<int> value);
    partial void Onban_idChanged();
    #endregion
		
		public tbHoaDonChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadonchitiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoadonchitiet_id
		{
			get
			{
				return this._hoadonchitiet_id;
			}
			set
			{
				if ((this._hoadonchitiet_id != value))
				{
					this.Onhoadonchitiet_idChanging(value);
					this.SendPropertyChanging();
					this._hoadonchitiet_id = value;
					this.SendPropertyChanged("hoadonchitiet_id");
					this.Onhoadonchitiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", DbType="Int")]
		public System.Nullable<int> hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int")]
		public System.Nullable<int> sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_soluong", DbType="Int")]
		public System.Nullable<int> sanpham_soluong
		{
			get
			{
				return this._sanpham_soluong;
			}
			set
			{
				if ((this._sanpham_soluong != value))
				{
					this.Onsanpham_soluongChanging(value);
					this.SendPropertyChanging();
					this._sanpham_soluong = value;
					this.SendPropertyChanged("sanpham_soluong");
					this.Onsanpham_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sanpham_dongia
		{
			get
			{
				return this._sanpham_dongia;
			}
			set
			{
				if ((this._sanpham_dongia != value))
				{
					this.Onsanpham_dongiaChanging(value);
					this.SendPropertyChanging();
					this._sanpham_dongia = value;
					this.SendPropertyChanged("sanpham_dongia");
					this.Onsanpham_dongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadonchitiet_thanhtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> hoadonchitiet_thanhtien
		{
			get
			{
				return this._hoadonchitiet_thanhtien;
			}
			set
			{
				if ((this._hoadonchitiet_thanhtien != value))
				{
					this.Onhoadonchitiet_thanhtienChanging(value);
					this.SendPropertyChanging();
					this._hoadonchitiet_thanhtien = value;
					this.SendPropertyChanged("hoadonchitiet_thanhtien");
					this.Onhoadonchitiet_thanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", DbType="Int")]
		public System.Nullable<int> ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLoaiBan")]
	public partial class tbLoaiBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loaiban_id;
		
		private string _loaiban_tenban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloaiban_idChanging(int value);
    partial void Onloaiban_idChanged();
    partial void Onloaiban_tenbanChanging(string value);
    partial void Onloaiban_tenbanChanged();
    #endregion
		
		public tbLoaiBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiban_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loaiban_id
		{
			get
			{
				return this._loaiban_id;
			}
			set
			{
				if ((this._loaiban_id != value))
				{
					this.Onloaiban_idChanging(value);
					this.SendPropertyChanging();
					this._loaiban_id = value;
					this.SendPropertyChanged("loaiban_id");
					this.Onloaiban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiban_tenban", DbType="NVarChar(MAX)")]
		public string loaiban_tenban
		{
			get
			{
				return this._loaiban_tenban;
			}
			set
			{
				if ((this._loaiban_tenban != value))
				{
					this.Onloaiban_tenbanChanging(value);
					this.SendPropertyChanging();
					this._loaiban_tenban = value;
					this.SendPropertyChanged("loaiban_tenban");
					this.Onloaiban_tenbanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLoaiSanPham")]
	public partial class tbLoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loaisanpham_id;
		
		private string _loaisanpham_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloaisanpham_idChanging(int value);
    partial void Onloaisanpham_idChanged();
    partial void Onloaisanpham_tenChanging(string value);
    partial void Onloaisanpham_tenChanged();
    #endregion
		
		public tbLoaiSanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loaisanpham_id
		{
			get
			{
				return this._loaisanpham_id;
			}
			set
			{
				if ((this._loaisanpham_id != value))
				{
					this.Onloaisanpham_idChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_id = value;
					this.SendPropertyChanged("loaisanpham_id");
					this.Onloaisanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_ten", DbType="NVarChar(MAX)")]
		public string loaisanpham_ten
		{
			get
			{
				return this._loaisanpham_ten;
			}
			set
			{
				if ((this._loaisanpham_ten != value))
				{
					this.Onloaisanpham_tenChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_ten = value;
					this.SendPropertyChanged("loaisanpham_ten");
					this.Onloaisanpham_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLoaiTinTuc")]
	public partial class tbLoaiTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loaitintuc_id;
		
		private string _loaitintuc_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloaitintuc_idChanging(int value);
    partial void Onloaitintuc_idChanged();
    partial void Onloaitintuc_tenChanging(string value);
    partial void Onloaitintuc_tenChanged();
    #endregion
		
		public tbLoaiTinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaitintuc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loaitintuc_id
		{
			get
			{
				return this._loaitintuc_id;
			}
			set
			{
				if ((this._loaitintuc_id != value))
				{
					this.Onloaitintuc_idChanging(value);
					this.SendPropertyChanging();
					this._loaitintuc_id = value;
					this.SendPropertyChanged("loaitintuc_id");
					this.Onloaitintuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaitintuc_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string loaitintuc_ten
		{
			get
			{
				return this._loaitintuc_ten;
			}
			set
			{
				if ((this._loaitintuc_ten != value))
				{
					this.Onloaitintuc_tenChanging(value);
					this.SendPropertyChanging();
					this._loaitintuc_ten = value;
					this.SendPropertyChanged("loaitintuc_ten");
					this.Onloaitintuc_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNhapHang")]
	public partial class tbNhapHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nhaphang_id;
		
		private string _nhaphang_nguoinhap;
		
		private string _nhaphang_nhacungcap;
		
		private System.Nullable<System.DateTime> _nhaphang_ngaynhap;
		
		private System.Nullable<decimal> _nhaphang_tongtien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhaphang_idChanging(string value);
    partial void Onnhaphang_idChanged();
    partial void Onnhaphang_nguoinhapChanging(string value);
    partial void Onnhaphang_nguoinhapChanged();
    partial void Onnhaphang_nhacungcapChanging(string value);
    partial void Onnhaphang_nhacungcapChanged();
    partial void Onnhaphang_ngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void Onnhaphang_ngaynhapChanged();
    partial void Onnhaphang_tongtienChanging(System.Nullable<decimal> value);
    partial void Onnhaphang_tongtienChanged();
    #endregion
		
		public tbNhapHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nhaphang_id
		{
			get
			{
				return this._nhaphang_id;
			}
			set
			{
				if ((this._nhaphang_id != value))
				{
					this.Onnhaphang_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_id = value;
					this.SendPropertyChanged("nhaphang_id");
					this.Onnhaphang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_nguoinhap", DbType="NVarChar(MAX)")]
		public string nhaphang_nguoinhap
		{
			get
			{
				return this._nhaphang_nguoinhap;
			}
			set
			{
				if ((this._nhaphang_nguoinhap != value))
				{
					this.Onnhaphang_nguoinhapChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_nguoinhap = value;
					this.SendPropertyChanged("nhaphang_nguoinhap");
					this.Onnhaphang_nguoinhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_nhacungcap", DbType="NVarChar(MAX)")]
		public string nhaphang_nhacungcap
		{
			get
			{
				return this._nhaphang_nhacungcap;
			}
			set
			{
				if ((this._nhaphang_nhacungcap != value))
				{
					this.Onnhaphang_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_nhacungcap = value;
					this.SendPropertyChanged("nhaphang_nhacungcap");
					this.Onnhaphang_nhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> nhaphang_ngaynhap
		{
			get
			{
				return this._nhaphang_ngaynhap;
			}
			set
			{
				if ((this._nhaphang_ngaynhap != value))
				{
					this.Onnhaphang_ngaynhapChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_ngaynhap = value;
					this.SendPropertyChanged("nhaphang_ngaynhap");
					this.Onnhaphang_ngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> nhaphang_tongtien
		{
			get
			{
				return this._nhaphang_tongtien;
			}
			set
			{
				if ((this._nhaphang_tongtien != value))
				{
					this.Onnhaphang_tongtienChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_tongtien = value;
					this.SendPropertyChanged("nhaphang_tongtien");
					this.Onnhaphang_tongtienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNhapHangChiTiet")]
	public partial class tbNhapHangChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nhaphangchitiet_id;
		
		private string _nhaphangchitiet_sanpham;
		
		private System.Nullable<int> _nhaphangchitiet_soluong;
		
		private System.Nullable<decimal> _nhaphangchitiet_dongia;
		
		private System.Nullable<decimal> _nhaphangchitiet_thanhtien;
		
		private string _nhaphang_id;
		
		private System.Nullable<int> _sanpham_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhaphangchitiet_idChanging(int value);
    partial void Onnhaphangchitiet_idChanged();
    partial void Onnhaphangchitiet_sanphamChanging(string value);
    partial void Onnhaphangchitiet_sanphamChanged();
    partial void Onnhaphangchitiet_soluongChanging(System.Nullable<int> value);
    partial void Onnhaphangchitiet_soluongChanged();
    partial void Onnhaphangchitiet_dongiaChanging(System.Nullable<decimal> value);
    partial void Onnhaphangchitiet_dongiaChanged();
    partial void Onnhaphangchitiet_thanhtienChanging(System.Nullable<decimal> value);
    partial void Onnhaphangchitiet_thanhtienChanged();
    partial void Onnhaphang_idChanging(string value);
    partial void Onnhaphang_idChanged();
    partial void Onsanpham_idChanging(System.Nullable<int> value);
    partial void Onsanpham_idChanged();
    #endregion
		
		public tbNhapHangChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nhaphangchitiet_id
		{
			get
			{
				return this._nhaphangchitiet_id;
			}
			set
			{
				if ((this._nhaphangchitiet_id != value))
				{
					this.Onnhaphangchitiet_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_id = value;
					this.SendPropertyChanged("nhaphangchitiet_id");
					this.Onnhaphangchitiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_sanpham", DbType="NVarChar(MAX)")]
		public string nhaphangchitiet_sanpham
		{
			get
			{
				return this._nhaphangchitiet_sanpham;
			}
			set
			{
				if ((this._nhaphangchitiet_sanpham != value))
				{
					this.Onnhaphangchitiet_sanphamChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_sanpham = value;
					this.SendPropertyChanged("nhaphangchitiet_sanpham");
					this.Onnhaphangchitiet_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_soluong", DbType="Int")]
		public System.Nullable<int> nhaphangchitiet_soluong
		{
			get
			{
				return this._nhaphangchitiet_soluong;
			}
			set
			{
				if ((this._nhaphangchitiet_soluong != value))
				{
					this.Onnhaphangchitiet_soluongChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_soluong = value;
					this.SendPropertyChanged("nhaphangchitiet_soluong");
					this.Onnhaphangchitiet_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> nhaphangchitiet_dongia
		{
			get
			{
				return this._nhaphangchitiet_dongia;
			}
			set
			{
				if ((this._nhaphangchitiet_dongia != value))
				{
					this.Onnhaphangchitiet_dongiaChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_dongia = value;
					this.SendPropertyChanged("nhaphangchitiet_dongia");
					this.Onnhaphangchitiet_dongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_thanhtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> nhaphangchitiet_thanhtien
		{
			get
			{
				return this._nhaphangchitiet_thanhtien;
			}
			set
			{
				if ((this._nhaphangchitiet_thanhtien != value))
				{
					this.Onnhaphangchitiet_thanhtienChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_thanhtien = value;
					this.SendPropertyChanged("nhaphangchitiet_thanhtien");
					this.Onnhaphangchitiet_thanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_id", DbType="NVarChar(MAX)")]
		public string nhaphang_id
		{
			get
			{
				return this._nhaphang_id;
			}
			set
			{
				if ((this._nhaphang_id != value))
				{
					this.Onnhaphang_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_id = value;
					this.SendPropertyChanged("nhaphang_id");
					this.Onnhaphang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int")]
		public System.Nullable<int> sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSanPham")]
	public partial class tbSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sanpham_id;
		
		private string _sanpham_ten;
		
		private System.Nullable<decimal> _sanpham_dongia;
		
		private System.Nullable<int> _loaisanpham_id;
		
		private string _loaisanpham_ten;
		
		private System.Nullable<int> _sanpham_soluong;
		
		private string _sanpham_hinhanh;
		
		private System.Nullable<int> _ban_id;
		
		private System.Nullable<decimal> _sanpham_thanhtien;
		
		private System.Nullable<int> _sanpham_soluongtoithieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsanpham_idChanging(int value);
    partial void Onsanpham_idChanged();
    partial void Onsanpham_tenChanging(string value);
    partial void Onsanpham_tenChanged();
    partial void Onsanpham_dongiaChanging(System.Nullable<decimal> value);
    partial void Onsanpham_dongiaChanged();
    partial void Onloaisanpham_idChanging(System.Nullable<int> value);
    partial void Onloaisanpham_idChanged();
    partial void Onloaisanpham_tenChanging(string value);
    partial void Onloaisanpham_tenChanged();
    partial void Onsanpham_soluongChanging(System.Nullable<int> value);
    partial void Onsanpham_soluongChanged();
    partial void Onsanpham_hinhanhChanging(string value);
    partial void Onsanpham_hinhanhChanged();
    partial void Onban_idChanging(System.Nullable<int> value);
    partial void Onban_idChanged();
    partial void Onsanpham_thanhtienChanging(System.Nullable<decimal> value);
    partial void Onsanpham_thanhtienChanged();
    partial void Onsanpham_soluongtoithieuChanging(System.Nullable<int> value);
    partial void Onsanpham_soluongtoithieuChanged();
    #endregion
		
		public tbSanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_ten", DbType="NVarChar(MAX)")]
		public string sanpham_ten
		{
			get
			{
				return this._sanpham_ten;
			}
			set
			{
				if ((this._sanpham_ten != value))
				{
					this.Onsanpham_tenChanging(value);
					this.SendPropertyChanging();
					this._sanpham_ten = value;
					this.SendPropertyChanged("sanpham_ten");
					this.Onsanpham_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_dongia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sanpham_dongia
		{
			get
			{
				return this._sanpham_dongia;
			}
			set
			{
				if ((this._sanpham_dongia != value))
				{
					this.Onsanpham_dongiaChanging(value);
					this.SendPropertyChanging();
					this._sanpham_dongia = value;
					this.SendPropertyChanged("sanpham_dongia");
					this.Onsanpham_dongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", DbType="Int")]
		public System.Nullable<int> loaisanpham_id
		{
			get
			{
				return this._loaisanpham_id;
			}
			set
			{
				if ((this._loaisanpham_id != value))
				{
					this.Onloaisanpham_idChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_id = value;
					this.SendPropertyChanged("loaisanpham_id");
					this.Onloaisanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_ten", DbType="NVarChar(MAX)")]
		public string loaisanpham_ten
		{
			get
			{
				return this._loaisanpham_ten;
			}
			set
			{
				if ((this._loaisanpham_ten != value))
				{
					this.Onloaisanpham_tenChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_ten = value;
					this.SendPropertyChanged("loaisanpham_ten");
					this.Onloaisanpham_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_soluong", DbType="Int")]
		public System.Nullable<int> sanpham_soluong
		{
			get
			{
				return this._sanpham_soluong;
			}
			set
			{
				if ((this._sanpham_soluong != value))
				{
					this.Onsanpham_soluongChanging(value);
					this.SendPropertyChanging();
					this._sanpham_soluong = value;
					this.SendPropertyChanged("sanpham_soluong");
					this.Onsanpham_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_hinhanh", DbType="NVarChar(MAX)")]
		public string sanpham_hinhanh
		{
			get
			{
				return this._sanpham_hinhanh;
			}
			set
			{
				if ((this._sanpham_hinhanh != value))
				{
					this.Onsanpham_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._sanpham_hinhanh = value;
					this.SendPropertyChanged("sanpham_hinhanh");
					this.Onsanpham_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", DbType="Int")]
		public System.Nullable<int> ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_thanhtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sanpham_thanhtien
		{
			get
			{
				return this._sanpham_thanhtien;
			}
			set
			{
				if ((this._sanpham_thanhtien != value))
				{
					this.Onsanpham_thanhtienChanging(value);
					this.SendPropertyChanging();
					this._sanpham_thanhtien = value;
					this.SendPropertyChanged("sanpham_thanhtien");
					this.Onsanpham_thanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_soluongtoithieu", DbType="Int")]
		public System.Nullable<int> sanpham_soluongtoithieu
		{
			get
			{
				return this._sanpham_soluongtoithieu;
			}
			set
			{
				if ((this._sanpham_soluongtoithieu != value))
				{
					this.Onsanpham_soluongtoithieuChanging(value);
					this.SendPropertyChanging();
					this._sanpham_soluongtoithieu = value;
					this.SendPropertyChanged("sanpham_soluongtoithieu");
					this.Onsanpham_soluongtoithieuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTaiKhoan")]
	public partial class tbTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _taikhoan_id;
		
		private string _taikhoan_hoten;
		
		private string _taikhoan_tentaikhoan;
		
		private string _taikhoan_matkhau;
		
		private string _taikhoan_hinhanh;
		
		private System.Nullable<bool> _taikhoan_gioitinh;
		
		private System.Nullable<System.DateTime> _taikhoan_ngaysinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontaikhoan_idChanging(int value);
    partial void Ontaikhoan_idChanged();
    partial void Ontaikhoan_hotenChanging(string value);
    partial void Ontaikhoan_hotenChanged();
    partial void Ontaikhoan_tentaikhoanChanging(string value);
    partial void Ontaikhoan_tentaikhoanChanged();
    partial void Ontaikhoan_matkhauChanging(string value);
    partial void Ontaikhoan_matkhauChanged();
    partial void Ontaikhoan_hinhanhChanging(string value);
    partial void Ontaikhoan_hinhanhChanged();
    partial void Ontaikhoan_gioitinhChanging(System.Nullable<bool> value);
    partial void Ontaikhoan_gioitinhChanged();
    partial void Ontaikhoan_ngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void Ontaikhoan_ngaysinhChanged();
    #endregion
		
		public tbTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int taikhoan_id
		{
			get
			{
				return this._taikhoan_id;
			}
			set
			{
				if ((this._taikhoan_id != value))
				{
					this.Ontaikhoan_idChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_id = value;
					this.SendPropertyChanged("taikhoan_id");
					this.Ontaikhoan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hoten", DbType="NVarChar(MAX)")]
		public string taikhoan_hoten
		{
			get
			{
				return this._taikhoan_hoten;
			}
			set
			{
				if ((this._taikhoan_hoten != value))
				{
					this.Ontaikhoan_hotenChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hoten = value;
					this.SendPropertyChanged("taikhoan_hoten");
					this.Ontaikhoan_hotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_tentaikhoan", DbType="NVarChar(255)")]
		public string taikhoan_tentaikhoan
		{
			get
			{
				return this._taikhoan_tentaikhoan;
			}
			set
			{
				if ((this._taikhoan_tentaikhoan != value))
				{
					this.Ontaikhoan_tentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_tentaikhoan = value;
					this.SendPropertyChanged("taikhoan_tentaikhoan");
					this.Ontaikhoan_tentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_matkhau", DbType="NVarChar(MAX)")]
		public string taikhoan_matkhau
		{
			get
			{
				return this._taikhoan_matkhau;
			}
			set
			{
				if ((this._taikhoan_matkhau != value))
				{
					this.Ontaikhoan_matkhauChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_matkhau = value;
					this.SendPropertyChanged("taikhoan_matkhau");
					this.Ontaikhoan_matkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hinhanh", DbType="NVarChar(MAX)")]
		public string taikhoan_hinhanh
		{
			get
			{
				return this._taikhoan_hinhanh;
			}
			set
			{
				if ((this._taikhoan_hinhanh != value))
				{
					this.Ontaikhoan_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hinhanh = value;
					this.SendPropertyChanged("taikhoan_hinhanh");
					this.Ontaikhoan_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_gioitinh", DbType="Bit")]
		public System.Nullable<bool> taikhoan_gioitinh
		{
			get
			{
				return this._taikhoan_gioitinh;
			}
			set
			{
				if ((this._taikhoan_gioitinh != value))
				{
					this.Ontaikhoan_gioitinhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_gioitinh = value;
					this.SendPropertyChanged("taikhoan_gioitinh");
					this.Ontaikhoan_gioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> taikhoan_ngaysinh
		{
			get
			{
				return this._taikhoan_ngaysinh;
			}
			set
			{
				if ((this._taikhoan_ngaysinh != value))
				{
					this.Ontaikhoan_ngaysinhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_ngaysinh = value;
					this.SendPropertyChanged("taikhoan_ngaysinh");
					this.Ontaikhoan_ngaysinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbGameChinhTa")]
	public partial class tbGameChinhTa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gamechinhta_id;
		
		private string _gamechinhta_noidung;
		
		private string _gamechinhta_dapansai;
		
		private string _gamechinhta_dapandung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongamechinhta_idChanging(int value);
    partial void Ongamechinhta_idChanged();
    partial void Ongamechinhta_noidungChanging(string value);
    partial void Ongamechinhta_noidungChanged();
    partial void Ongamechinhta_dapansaiChanging(string value);
    partial void Ongamechinhta_dapansaiChanged();
    partial void Ongamechinhta_dapandungChanging(string value);
    partial void Ongamechinhta_dapandungChanged();
    #endregion
		
		public tbGameChinhTa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gamechinhta_id
		{
			get
			{
				return this._gamechinhta_id;
			}
			set
			{
				if ((this._gamechinhta_id != value))
				{
					this.Ongamechinhta_idChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_id = value;
					this.SendPropertyChanged("gamechinhta_id");
					this.Ongamechinhta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_noidung", DbType="NVarChar(MAX)")]
		public string gamechinhta_noidung
		{
			get
			{
				return this._gamechinhta_noidung;
			}
			set
			{
				if ((this._gamechinhta_noidung != value))
				{
					this.Ongamechinhta_noidungChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_noidung = value;
					this.SendPropertyChanged("gamechinhta_noidung");
					this.Ongamechinhta_noidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_dapansai", DbType="NVarChar(MAX)")]
		public string gamechinhta_dapansai
		{
			get
			{
				return this._gamechinhta_dapansai;
			}
			set
			{
				if ((this._gamechinhta_dapansai != value))
				{
					this.Ongamechinhta_dapansaiChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_dapansai = value;
					this.SendPropertyChanged("gamechinhta_dapansai");
					this.Ongamechinhta_dapansaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_dapandung", DbType="NVarChar(MAX)")]
		public string gamechinhta_dapandung
		{
			get
			{
				return this._gamechinhta_dapandung;
			}
			set
			{
				if ((this._gamechinhta_dapandung != value))
				{
					this.Ongamechinhta_dapandungChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_dapandung = value;
					this.SendPropertyChanged("gamechinhta_dapandung");
					this.Ongamechinhta_dapandungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
