#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanHangg
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbGameHocTap")]
	public partial class dbcsdlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbGameChinhTa(tbGameChinhTa instance);
    partial void UpdatetbGameChinhTa(tbGameChinhTa instance);
    partial void DeletetbGameChinhTa(tbGameChinhTa instance);
    partial void InserttbTaiKhoan(tbTaiKhoan instance);
    partial void UpdatetbTaiKhoan(tbTaiKhoan instance);
    partial void DeletetbTaiKhoan(tbTaiKhoan instance);
    partial void InserttbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void UpdatetbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void DeletetbGameDuoiHinhBatChu(tbGameDuoiHinhBatChu instance);
    partial void InserttbKhoiLop(tbKhoiLop instance);
    partial void UpdatetbKhoiLop(tbKhoiLop instance);
    partial void DeletetbKhoiLop(tbKhoiLop instance);
    partial void InserttbManGame(tbManGame instance);
    partial void UpdatetbManGame(tbManGame instance);
    partial void DeletetbManGame(tbManGame instance);
    #endregion
		
		public dbcsdlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbGameHocTapConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbGameChinhTa> tbGameChinhTas
		{
			get
			{
				return this.GetTable<tbGameChinhTa>();
			}
		}
		
		public System.Data.Linq.Table<tbTaiKhoan> tbTaiKhoans
		{
			get
			{
				return this.GetTable<tbTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tbGameDuoiHinhBatChu> tbGameDuoiHinhBatChus
		{
			get
			{
				return this.GetTable<tbGameDuoiHinhBatChu>();
			}
		}
		
		public System.Data.Linq.Table<tbKhoiLop> tbKhoiLops
		{
			get
			{
				return this.GetTable<tbKhoiLop>();
			}
		}
		
		public System.Data.Linq.Table<tbManGame> tbManGames
		{
			get
			{
				return this.GetTable<tbManGame>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbGameChinhTa")]
	public partial class tbGameChinhTa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gamechinhta_id;
		
		private string _gamechinhta_noidung;
		
		private string _gamechinhta_dapan;
		
		private string _gamechinhta_dapansai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongamechinhta_idChanging(int value);
    partial void Ongamechinhta_idChanged();
    partial void Ongamechinhta_noidungChanging(string value);
    partial void Ongamechinhta_noidungChanged();
    partial void Ongamechinhta_dapanChanging(string value);
    partial void Ongamechinhta_dapanChanged();
    partial void Ongamechinhta_dapansaiChanging(string value);
    partial void Ongamechinhta_dapansaiChanged();
    #endregion
		
		public tbGameChinhTa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gamechinhta_id
		{
			get
			{
				return this._gamechinhta_id;
			}
			set
			{
				if ((this._gamechinhta_id != value))
				{
					this.Ongamechinhta_idChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_id = value;
					this.SendPropertyChanged("gamechinhta_id");
					this.Ongamechinhta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_noidung", DbType="NVarChar(MAX)")]
		public string gamechinhta_noidung
		{
			get
			{
				return this._gamechinhta_noidung;
			}
			set
			{
				if ((this._gamechinhta_noidung != value))
				{
					this.Ongamechinhta_noidungChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_noidung = value;
					this.SendPropertyChanged("gamechinhta_noidung");
					this.Ongamechinhta_noidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_dapan", DbType="NVarChar(MAX)")]
		public string gamechinhta_dapan
		{
			get
			{
				return this._gamechinhta_dapan;
			}
			set
			{
				if ((this._gamechinhta_dapan != value))
				{
					this.Ongamechinhta_dapanChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_dapan = value;
					this.SendPropertyChanged("gamechinhta_dapan");
					this.Ongamechinhta_dapanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gamechinhta_dapansai", DbType="NVarChar(MAX)")]
		public string gamechinhta_dapansai
		{
			get
			{
				return this._gamechinhta_dapansai;
			}
			set
			{
				if ((this._gamechinhta_dapansai != value))
				{
					this.Ongamechinhta_dapansaiChanging(value);
					this.SendPropertyChanging();
					this._gamechinhta_dapansai = value;
					this.SendPropertyChanged("gamechinhta_dapansai");
					this.Ongamechinhta_dapansaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTaiKhoan")]
	public partial class tbTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _taikhoan_id;
		
		private string _taikhoan_hoten;
		
		private string _taikhoan_tentaikhoan;
		
		private string _taikhoan_matkhau;
		
		private string _taikhoan_hinhanh;
		
		private System.Nullable<bool> _taikhoan_gioitinh;
		
		private System.Nullable<System.DateTime> _taikhoan_ngaysinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontaikhoan_idChanging(int value);
    partial void Ontaikhoan_idChanged();
    partial void Ontaikhoan_hotenChanging(string value);
    partial void Ontaikhoan_hotenChanged();
    partial void Ontaikhoan_tentaikhoanChanging(string value);
    partial void Ontaikhoan_tentaikhoanChanged();
    partial void Ontaikhoan_matkhauChanging(string value);
    partial void Ontaikhoan_matkhauChanged();
    partial void Ontaikhoan_hinhanhChanging(string value);
    partial void Ontaikhoan_hinhanhChanged();
    partial void Ontaikhoan_gioitinhChanging(System.Nullable<bool> value);
    partial void Ontaikhoan_gioitinhChanged();
    partial void Ontaikhoan_ngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void Ontaikhoan_ngaysinhChanged();
    #endregion
		
		public tbTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int taikhoan_id
		{
			get
			{
				return this._taikhoan_id;
			}
			set
			{
				if ((this._taikhoan_id != value))
				{
					this.Ontaikhoan_idChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_id = value;
					this.SendPropertyChanged("taikhoan_id");
					this.Ontaikhoan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hoten", DbType="NVarChar(MAX)")]
		public string taikhoan_hoten
		{
			get
			{
				return this._taikhoan_hoten;
			}
			set
			{
				if ((this._taikhoan_hoten != value))
				{
					this.Ontaikhoan_hotenChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hoten = value;
					this.SendPropertyChanged("taikhoan_hoten");
					this.Ontaikhoan_hotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_tentaikhoan", DbType="NVarChar(255)")]
		public string taikhoan_tentaikhoan
		{
			get
			{
				return this._taikhoan_tentaikhoan;
			}
			set
			{
				if ((this._taikhoan_tentaikhoan != value))
				{
					this.Ontaikhoan_tentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_tentaikhoan = value;
					this.SendPropertyChanged("taikhoan_tentaikhoan");
					this.Ontaikhoan_tentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_matkhau", DbType="NVarChar(MAX)")]
		public string taikhoan_matkhau
		{
			get
			{
				return this._taikhoan_matkhau;
			}
			set
			{
				if ((this._taikhoan_matkhau != value))
				{
					this.Ontaikhoan_matkhauChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_matkhau = value;
					this.SendPropertyChanged("taikhoan_matkhau");
					this.Ontaikhoan_matkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hinhanh", DbType="NVarChar(MAX)")]
		public string taikhoan_hinhanh
		{
			get
			{
				return this._taikhoan_hinhanh;
			}
			set
			{
				if ((this._taikhoan_hinhanh != value))
				{
					this.Ontaikhoan_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hinhanh = value;
					this.SendPropertyChanged("taikhoan_hinhanh");
					this.Ontaikhoan_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_gioitinh", DbType="Bit")]
		public System.Nullable<bool> taikhoan_gioitinh
		{
			get
			{
				return this._taikhoan_gioitinh;
			}
			set
			{
				if ((this._taikhoan_gioitinh != value))
				{
					this.Ontaikhoan_gioitinhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_gioitinh = value;
					this.SendPropertyChanged("taikhoan_gioitinh");
					this.Ontaikhoan_gioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> taikhoan_ngaysinh
		{
			get
			{
				return this._taikhoan_ngaysinh;
			}
			set
			{
				if ((this._taikhoan_ngaysinh != value))
				{
					this.Ontaikhoan_ngaysinhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_ngaysinh = value;
					this.SendPropertyChanged("taikhoan_ngaysinh");
					this.Ontaikhoan_ngaysinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbGameDuoiHinhBatChu")]
	public partial class tbGameDuoiHinhBatChu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _duoihinhbatchu_id;
		
		private string _duoihinhbatchu_hinhanh;
		
		private string _duoihinhbatchu_dapan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onduoihinhbatchu_idChanging(int value);
    partial void Onduoihinhbatchu_idChanged();
    partial void Onduoihinhbatchu_hinhanhChanging(string value);
    partial void Onduoihinhbatchu_hinhanhChanged();
    partial void Onduoihinhbatchu_dapanChanging(string value);
    partial void Onduoihinhbatchu_dapanChanged();
    #endregion
		
		public tbGameDuoiHinhBatChu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int duoihinhbatchu_id
		{
			get
			{
				return this._duoihinhbatchu_id;
			}
			set
			{
				if ((this._duoihinhbatchu_id != value))
				{
					this.Onduoihinhbatchu_idChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_id = value;
					this.SendPropertyChanged("duoihinhbatchu_id");
					this.Onduoihinhbatchu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_hinhanh", DbType="NVarChar(MAX)")]
		public string duoihinhbatchu_hinhanh
		{
			get
			{
				return this._duoihinhbatchu_hinhanh;
			}
			set
			{
				if ((this._duoihinhbatchu_hinhanh != value))
				{
					this.Onduoihinhbatchu_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_hinhanh = value;
					this.SendPropertyChanged("duoihinhbatchu_hinhanh");
					this.Onduoihinhbatchu_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duoihinhbatchu_dapan", DbType="NVarChar(MAX)")]
		public string duoihinhbatchu_dapan
		{
			get
			{
				return this._duoihinhbatchu_dapan;
			}
			set
			{
				if ((this._duoihinhbatchu_dapan != value))
				{
					this.Onduoihinhbatchu_dapanChanging(value);
					this.SendPropertyChanging();
					this._duoihinhbatchu_dapan = value;
					this.SendPropertyChanged("duoihinhbatchu_dapan");
					this.Onduoihinhbatchu_dapanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbKhoiLop")]
	public partial class tbKhoiLop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khoilop_id;
		
		private string _khoilop_khoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkhoilop_idChanging(int value);
    partial void Onkhoilop_idChanged();
    partial void Onkhoilop_khoiChanging(string value);
    partial void Onkhoilop_khoiChanged();
    #endregion
		
		public tbKhoiLop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoilop_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khoilop_id
		{
			get
			{
				return this._khoilop_id;
			}
			set
			{
				if ((this._khoilop_id != value))
				{
					this.Onkhoilop_idChanging(value);
					this.SendPropertyChanging();
					this._khoilop_id = value;
					this.SendPropertyChanged("khoilop_id");
					this.Onkhoilop_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoilop_khoi", DbType="NVarChar(MAX)")]
		public string khoilop_khoi
		{
			get
			{
				return this._khoilop_khoi;
			}
			set
			{
				if ((this._khoilop_khoi != value))
				{
					this.Onkhoilop_khoiChanging(value);
					this.SendPropertyChanging();
					this._khoilop_khoi = value;
					this.SendPropertyChanged("khoilop_khoi");
					this.Onkhoilop_khoiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbManGame")]
	public partial class tbManGame : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mangame_id;
		
		private string _mangame_man;
		
		private System.Nullable<int> _khoilop_id;
		
		private string _khoilop_khoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmangame_idChanging(int value);
    partial void Onmangame_idChanged();
    partial void Onmangame_manChanging(string value);
    partial void Onmangame_manChanged();
    partial void Onkhoilop_idChanging(System.Nullable<int> value);
    partial void Onkhoilop_idChanged();
    partial void Onkhoilop_khoiChanging(string value);
    partial void Onkhoilop_khoiChanged();
    #endregion
		
		public tbManGame()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mangame_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mangame_id
		{
			get
			{
				return this._mangame_id;
			}
			set
			{
				if ((this._mangame_id != value))
				{
					this.Onmangame_idChanging(value);
					this.SendPropertyChanging();
					this._mangame_id = value;
					this.SendPropertyChanged("mangame_id");
					this.Onmangame_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mangame_man", DbType="NVarChar(MAX)")]
		public string mangame_man
		{
			get
			{
				return this._mangame_man;
			}
			set
			{
				if ((this._mangame_man != value))
				{
					this.Onmangame_manChanging(value);
					this.SendPropertyChanging();
					this._mangame_man = value;
					this.SendPropertyChanged("mangame_man");
					this.Onmangame_manChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoilop_id", DbType="Int")]
		public System.Nullable<int> khoilop_id
		{
			get
			{
				return this._khoilop_id;
			}
			set
			{
				if ((this._khoilop_id != value))
				{
					this.Onkhoilop_idChanging(value);
					this.SendPropertyChanging();
					this._khoilop_id = value;
					this.SendPropertyChanged("khoilop_id");
					this.Onkhoilop_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoilop_khoi", DbType="NVarChar(MAX)")]
		public string khoilop_khoi
		{
			get
			{
				return this._khoilop_khoi;
			}
			set
			{
				if ((this._khoilop_khoi != value))
				{
					this.Onkhoilop_khoiChanging(value);
					this.SendPropertyChanging();
					this._khoilop_khoi = value;
					this.SendPropertyChanged("khoilop_khoi");
					this.Onkhoilop_khoiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
